### ISSUE TITLE
TEMA - FOUNDATION FRAMEWORK

### ISSUE THREAD

**Issue by GuilhermeOmetto** [woliveiras/woliveiras.github.io#10]
Gostaria de ler sobre Foundation na concepção de e-mails.

**Comment by woliveiras** [comment]
Você fala sobre usar o [Ink](http://foundation.zurb.com/emails.html), mano?

**Comment by GuilhermeOmetto** [comment]
Sim, esse carinha ai mesmo. Dei a sugestão pois sempre construi emails mkt na unha e dependendo da complexidade do layout o job pode ficar bem demorado e pesquisando sobre ferramentas achei ele.

**Comment by woliveiras** [comment]
Rapaz, nunca usei ele. Eu teria de dar uma estudada legal.

Vou deixar a issue no esquema e assim que der um tempo vou estudar ele. 😄 

Você já está usando?

**Comment by GuilhermeOmetto** [comment]
Ainda não, mas pretendo aprender tbm, não sei como é o dia-a-dia de outros deves que produzem mails.. talvez algum outro colega possa falar com mais propriedade tbm.

**Comment by woliveiras** [comment]
Sim mano

Seria interessante levarmos sua dúvida pro forum: https://github.com/frontendbr/forum

Que tal?

**Comment by GuilhermeOmetto** [comment]
Claro pode ser sim, mas não deixa de ser tema pro seu blogue =D

**Comment by woliveiras** [comment]
\o/

**Comment by woliveiras** [comment]
Atualizei o tema do blog, jovem.

Obrigado pela contribuição.
