### ISSUE TITLE
Fix "Conhece-te a ti mesmo" post

### ISSUE THREAD

**Issue by gabriel-brito** [woliveiras/woliveiras.github.io#12]
There is some sentence in portuguese that is incomprehensible.
I tried to fix but my computer change all your folders
> Não é o stress que ruim, mas a maneira como reagimos a ele.

**Comment by woliveiras** [comment]
Fixed: https://github.com/woliveiras/woliveiras.github.io/commit/7e27bd187c171a30a4f763d2ccec27d87f3e7f9a
