### ISSUE TITLE
Um pequeno typo

### ISSUE THREAD

**Issue by ericp3reira** [woliveiras/woliveiras.github.io#13]
Na linha `<strong class="article-nav-caption">Póximo</strong>` imagino que deveria ser "Próximo".

Desculpe ser chato, mas imagino que esses pequenos erros passam despercebidos e eu gostaria de ser avisado caso o site fosse meu...

E parabéns pelos posts! Gostei muito, principalmente como um Front-End iniciante. =D

**Comment by woliveiras** [comment]
\o/

Valeu, @ericp3reira 

`Desculpe ser chato`... Nunca é chato, cara. É uma contribuição.

Eu agradeço demais pela revisão por que realmente muita coisa passa despercebida. 😄

**Comment by woliveiras** [comment]
Ajeitei lá @ericp3reira
