### ISSUE TITLE
Endereço para LinkedIn incorreto no rodapé

### ISSUE THREAD

**Issue by felipemfp** [woliveiras/woliveiras.github.io#15]
@woliveiras, tentei acessar seu LinkedIn pelo endereço fornecido no rodapé (https://br.linkedin.com/in/woliveira542), mas o perfil não é encontrado:

![image](https://user-images.githubusercontent.com/8146112/34801598-50c3faa0-f648-11e7-954d-852622973f90.png)

**Comment by woliveiras** [comment]
:scream: 

Obrigado pelo alerta, @felipemfp 

Vaou ajustar.
