### ISSUE TITLE
Suguestão - Aumentar um pouco a fonte do footer

### ISSUE THREAD

**Issue by isaacmeira** [woliveiras/woliveiras.github.io#18]
Olá willian tudo certo ? 
Estava checando seu site e vi que o sr. poderia aumentar a letra da fonte do footer ou deixá-la em bold, pois as cores estão contratando muito e fica dificil na visualização, digo nas fontes alaranjadas, also, parabéns pelo trabalho :)

**Comment by woliveiras** [comment]
Opa! 

Obrigado pela sugestão, @isaacmeira.

Vou atualizar isso.
